# Generated by Django 3.0.1 on 2022-09-20 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_sent_time_and_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-sent_on']},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='sent_time_and_date',
            new_name='sent_on',
        ),
    ]
