# Generated by Django 3.0.1 on 2022-09-21 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact_responded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-sent_on'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
    ]
