# Generated by Django 3.0.1 on 2022-09-21 02:27

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='image',
        ),
        migrations.AddField(
            model_name='productreview',
            name='rating',
            # field=models.PositiveSmallIntegerField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
