# Generated by Django 3.0.1 on 2022-09-21 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220921_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='rating',
        ),
    ]
