# Generated by Django 3.0.1 on 2022-09-21 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_productreview_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='rating',
        ),
    ]
