# Generated by Django 3.0.1 on 2022-09-21 03:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_productreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='review',
            field=models.TextField(help_text='Enter a review for this product', max_length=1000, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
