# Generated by Django 3.0.1 on 2022-09-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='display_on_website',
            field=models.BooleanField(default=False),
        ),
    ]
