# Generated by Django 3.0.1 on 2022-09-21 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_testimonial_display_on_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='sent_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
