# Generated by Django 3.0.1 on 2022-09-19 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220910_1534'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
